// Code generated by scripts/gen-rewards-types.mjs — DO NOT EDIT.
//
// Source of truth: pkg/rewards/tiers.go
// Regenerate with: node scripts/gen-rewards-types.mjs
//
// Phase 1 of RFC #8862 moved the canonical contributor-ladder
// definition to Go. The CI drift check at
// .github/workflows/rewards-types-drift.yml re-runs the generator and
// fails the build if this file does not match the Go source.

import type { ContributorLevel } from './rewards'

export const CONTRIBUTOR_LEVELS_GENERATED: ContributorLevel[] = [
  {
    rank: 1,
    name: "Observer",
    icon: "Telescope",
    iconPath: "m19 11-8-8c-.9-.9-2.3-.9-3.2 0L2 9.5a1 1 0 0 0 0 1.4l7.1 7.1a1 1 0 0 0 1.4 0L19 11ZM8.5 8.5 13 13M16 2l5 5M22 22l-3-3M7 22l-1-3M10 22l1-3",
    minCoins: 0,
    color: "gray",
    bgClass: "bg-gray-500/20",
    textClass: "text-muted-foreground",
    borderClass: "border-gray-500/30",
  },
  {
    rank: 2,
    name: "Explorer",
    icon: "Compass",
    iconPath: "m16.24 7.76-1.41 4.95-4.95 1.41 1.41-4.95 4.95-1.41ZM12 22c5.52 0 10-4.48 10-10S17.52 2 12 2 2 6.48 2 12s4.48 10 10 10Z",
    minCoins: 500,
    color: "blue",
    bgClass: "bg-blue-500/20",
    textClass: "text-blue-400",
    borderClass: "border-blue-500/30",
  },
  {
    rank: 3,
    name: "Navigator",
    icon: "Map",
    iconPath: "M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3V6ZM9 3v15M15 6v15",
    minCoins: 2000,
    color: "cyan",
    bgClass: "bg-cyan-500/20",
    textClass: "text-cyan-400",
    borderClass: "border-cyan-500/30",
  },
  {
    rank: 4,
    name: "Pilot",
    icon: "Rocket",
    iconPath: "M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09ZM12 15l-3.5 3.5M20.3 3.7a2.32 2.32 0 0 0-3.3 0c-1.2 1.2-1.9 2.5-2.2 3.7c-.1.3 0 .6.2.8c.2.2.5.3.8.2c1.2-.3 2.5-1 3.7-2.2a2.32 2.32 0 0 0 0-3.3ZM8.8 15.8l-2.2 2.2M16 8l-3.5 3.5M12 2a21.19 21.19 0 0 0-1 9c0 .7.3 1.4.9 1.9s.9.9 1.9.9c3.1 0 6.2-.3 9-1c.7-.2 1.2-.7 1.4-1.4a21.24 21.24 0 0 0-1-9",
    minCoins: 5000,
    color: "green",
    bgClass: "bg-green-500/20",
    textClass: "text-green-400",
    borderClass: "border-green-500/30",
  },
  {
    rank: 5,
    name: "Commander",
    icon: "Shield",
    iconPath: "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
    minCoins: 15000,
    color: "purple",
    bgClass: "bg-purple-500/20",
    textClass: "text-purple-400",
    borderClass: "border-purple-500/30",
  },
  {
    rank: 6,
    name: "Captain",
    icon: "Star",
    iconPath: "M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z",
    minCoins: 50000,
    color: "orange",
    bgClass: "bg-orange-500/20",
    textClass: "text-orange-400",
    borderClass: "border-orange-500/30",
  },
  {
    rank: 7,
    name: "Admiral",
    icon: "Crown",
    iconPath: "m2 4 3 10h14l3-10-6 7-4-7-4 7-6-7Zm3 16h14",
    minCoins: 150000,
    color: "red",
    bgClass: "bg-red-500/20",
    textClass: "text-red-400",
    borderClass: "border-red-500/30",
  },
  {
    rank: 8,
    name: "Legend",
    icon: "Sparkles",
    iconPath: "m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z",
    minCoins: 500000,
    color: "yellow",
    bgClass: "bg-linear-to-r from-yellow-400/30 via-amber-300/30 to-yellow-500/30",
    textClass: "text-yellow-300",
    borderClass: "border-yellow-400/50",
  },
]

/** Point values for GitHub contributions (#8862 Phase 4). */
export const GITHUB_SCORING_GENERATED = {
  BugIssue: 300,
  FeatureIssue: 100,
  OtherIssue: 50,
  PROpened: 200,
  PRMerged: 500,
} as const
