import type { Source, Criterion } from './types'

const CRITERIA: Criterion[] = [
  {
    id: 'fullsend:test-coverage',
    source: 'fullsend',
    level: 2,
    category: 'readiness',
    name: 'Test coverage threshold',
    description: 'Documented or enforced test coverage floor.',
    rationale: 'Fullsend treats coverage as a readiness prerequisite: agents cannot be trusted on an untested codebase.',
    detection: { type: 'any-of', pattern: ['codecov.yml', '.codecov.yml', 'coverage.yml', '.github/workflows/coverage-gate.yml'] },
  },
  {
    id: 'fullsend:ci-cd-maturity',
    source: 'fullsend',
    level: 2,
    category: 'readiness',
    name: 'CI/CD pipeline',
    description: 'A working CI/CD pipeline that runs on every PR.',
    rationale: 'The second fullsend readiness prerequisite — a repo without CI cannot gate agent work.',
    detection: { type: 'any-of', pattern: ['.github/workflows/'] },
  },
  {
    id: 'fullsend:auto-merge-policy',
    source: 'fullsend',
    level: 3,
    category: 'autonomy',
    name: 'Auto-merge policy',
    description: 'Explicit policy for when PRs auto-merge vs. escalate to humans.',
    rationale: 'Fullsend\'s "When to auto-merge vs. escalate to humans" dimension — this is where the autonomy boundary gets drawn.',
    detection: { type: 'any-of', pattern: ['.github/auto-merge.yml', '.prow.yaml', 'tide.yaml', '.github/workflows/auto-merge.yml'] },
  },
  {
    id: 'fullsend:branch-protection-doc',
    source: 'fullsend',
    level: 3,
    category: 'governance',
    name: 'Branch protection documentation',
    description: 'Documented branch protection rules (required reviews, status checks).',
    rationale: 'Autonomy only works on top of explicit protection rules — fullsend treats these as the fence inside which agents may act.',
    detection: { type: 'any-of', pattern: ['docs/branch-protection.md', 'docs/governance.md', '.github/branch-protection.yml'] },
  },
  {
    id: 'fullsend:production-feedback',
    source: 'fullsend',
    level: 4,
    category: 'observability',
    name: 'Production feedback signal',
    description: 'A mechanism that feeds production observations back into the development loop.',
    rationale: 'Fullsend\'s Production Feedback dimension: platform execution signals should inform what agents work on and how they assess risk.',
    detection: { type: 'any-of', pattern: ['monitoring/', 'grafana/', '.github/workflows/post-deploy-check.yml', 'scripts/production-feedback.mjs'] },
  },
  {
    id: 'fullsend:observability-runbook',
    source: 'fullsend',
    level: 4,
    category: 'observability',
    name: 'Observability runbook',
    description: 'A runbook or guide describing how humans debug autonomous behavior.',
    rationale: 'Fullsend\'s Operational Observability question: how do humans understand what the autonomous system is doing when it goes wrong?',
    detection: { type: 'any-of', pattern: ['docs/runbook.md', 'docs/runbooks/', 'RUNBOOK.md', 'docs/operations/'] },
  },
  {
    id: 'fullsend:risk-assessment',
    source: 'fullsend',
    level: 4,
    category: 'autonomy',
    name: 'Risk assessment config',
    description: 'A config that lets the agent assess blast radius before acting.',
    rationale: 'Fullsend emphasizes that agents need a risk model to know when to escalate — static config is the minimum viable version.',
    detection: { type: 'any-of', pattern: ['.github/risk-assessment.yml', 'docs/risk-tiers.md', '.github/workflows/tier-classifier.yml'] },
  },
  {
    id: 'fullsend:rollback-drill',
    source: 'fullsend',
    level: 3,
    category: 'readiness',
    name: 'Rollback drill',
    description: 'A documented or automated rollback procedure.',
    rationale: 'Fullsend: autonomy requires the ability to undo, not just to do.',
    detection: { type: 'any-of', pattern: ['docs/rollback.md', '.github/workflows/rollback.yml', 'scripts/rollback.sh'] },
  },
]

export const fullsendSource: Source = {
  id: 'fullsend',
  name: 'Fullsend',
  url: 'https://github.com/fullsend-ai/fullsend',
  citation: 'Fullsend: Vision for fully autonomous agentic engineering. github.com/fullsend-ai/fullsend',
  definesLevels: false,
  criteria: CRITERIA,
}
